title:              DataInfinite
email:              scvslsravikiran@gmail.com
description:        Infinite your Data skills
author:             SCVSLS Ravi Kiran
baseurl:            ""
url:                "https://datainfinite.github.io"

# Social Profiles
twitter_username:   scvslsravikiran
github_username:    scvslsravikiran
facebook_username:  scvslsravikiran
instagram_username:  
linkedin_username: scvsls-ravikiran
researchgate_username: Ravi-Kiran-S-C-V-S-L-S

# Add yourgoogle-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

permalink: /:categories/:title:output_ext
highlighter: rouge
